-- ============================

-- Questo file è stato creato con la utility dblook di Derby.
-- Indicatore data/ora: 2023-06-12 23:07:22.349
-- Database di origine: Tum4WorldDB
-- URL di connessione: jdbc:derby://localhost:1527/Tum4WorldDB;user=APP;
-- appendLogs: false

-- ----------------------------------------------
-- Istruzioni DDL per tabelle
-- ----------------------------------------------

CREATE TABLE "APP"."SUBSCRIPTIONS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "USER_ID" INTEGER, "ACTIVITY_ID" INTEGER);

CREATE TABLE "APP"."USERS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(16) NOT NULL, "SURNAME" VARCHAR(32), "BIRTH_DATE" DATE, "EMAIL_ADDRESS" VARCHAR(128) NOT NULL, "TELEPHONE_NUMBER" VARCHAR(32), "ROLE" INTEGER, "USERNAME" VARCHAR(64), "PASSWORD" VARCHAR(32));

CREATE TABLE "APP"."ACTIVITIES" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "NAME" VARCHAR(64), "DESCRIPTION" LONG VARCHAR, "IMAGE_NAME" VARCHAR(32));

CREATE TABLE "APP"."DONATIONS" ("ID" INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1), "CONTRIBUTOR" INTEGER, "AMOUNT" DOUBLE, "DATE" DATE);

-- ----------------------------------------------
-- Istruzioni DDL per chiavi
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "APP"."USERS" ADD CONSTRAINT "USERS_id" PRIMARY KEY ("ID");

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "USERS_username" UNIQUE ("USERNAME");

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "USERS_pk" UNIQUE ("NAME");

ALTER TABLE "APP"."SUBSCRIPTIONS" ADD CONSTRAINT "SUBSCRIPTIONS_pk" PRIMARY KEY ("ID");

ALTER TABLE "APP"."ACTIVITIES" ADD CONSTRAINT "ACTIVITIES_pk" PRIMARY KEY ("ID");

ALTER TABLE "APP"."ACTIVITIES" ADD CONSTRAINT "ACTIVITIES_pk2" UNIQUE ("NAME");

ALTER TABLE "APP"."DONATIONS" ADD CONSTRAINT "DONATIONS_pk" PRIMARY KEY ("ID");

-- FOREIGN
ALTER TABLE "APP"."SUBSCRIPTIONS" ADD CONSTRAINT "SUBSCRIPTIONS_ACTIVITIES_ID_fk" FOREIGN KEY ("ACTIVITY_ID") REFERENCES "APP"."ACTIVITIES" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."SUBSCRIPTIONS" ADD CONSTRAINT "SUBSCRIPTIONS_USERS_ID_fk" FOREIGN KEY ("USER_ID") REFERENCES "APP"."USERS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."DONATIONS" ADD CONSTRAINT "DONATIONS_USERS_ID_fk" FOREIGN KEY ("CONTRIBUTOR") REFERENCES "APP"."USERS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

